name: finner
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  auto_route: ^5.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  injectable: ^1.5.3

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
flutter:
  uses-material-design: true
