name: finner
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  auto_route: ^5.0.1
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  firebase_core: ^1.22.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_keyboard_visibility: ^5.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  injectable: ^1.5.3

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
flutter:
  uses-material-design: true

assets:
  - assets/app_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
